### ISSUE TITLE
'projects' command fails with KeyError: 'name'

### ISSUE THREAD

**Issue by jeremygram** [bitbar/testdroid-api-client-python#129]
I have 4 projects created on the Bitbar dashboard.  When I run `testdroid projects` I get this error:

```
$ testdroid projects
Traceback (most recent call last):
  File "/usr/local/bin/testdroid", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/testdroid/__init__.py", line 1175, in main
    testdroid.cli(parser, commands)
  File "/usr/local/lib/python3.7/site-packages/testdroid/__init__.py", line 1167, in cli
    print(command(*args[1:]) or "")
  File "/usr/local/lib/python3.7/site-packages/testdroid/__init__.py", line 401, in print_projects
    print("Projects for %s <%s>:" % (me['name'], me['email']))
KeyError: 'name'
```

The `testdroid me` command works as expected and outputs all of my account info.  Testdroid was installed with `pip install testdroid`.

Testdroid version: 2.69.3
Python version: 3.7.6

**Comment by jeremygram** [comment]
The 'name' and 'email' fields no longer exist.  They are now 'firstName, 'lastName', 'mainUserEmail'.

**Comment by jeremygram** [comment]
Opened a pull request: https://github.com/bitbar/testdroid-api-client-python/pull/130
